const actionTypes = Object.freeze({
  // EXAMPLE
  EXAMPLE_ACTION_TYPE: 'EXAMPLE_ACTION_TYPE',

  // CATEGORIES
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_DATA: 'GET_CATEGORIES_DATA',
  GET_CATEGORIES_ERROR: 'GET_CATEGORIES_ERROR',

  GET_CATEGORY_DETAIL_REQUEST: 'GET_CATEGORY_DETAIL_REQUEST',
  GET_CATEGORY_DETAIL_DATA: 'GET_CATEGORY_DETAIL_DATA',
  GET_CATEGORY_DETAIL_ERROR: 'GET_CATEGORY_DETAIL_ERROR',

  // EXERCISE
  GET_EXERCISE_REQUEST: 'GET_EXERCISE_REQUEST',
  GET_EXERCISE_DATA: 'GET_EXERCISE_DATA',
  GET_EXERCISE_ERROR: 'GET_EXERCISE_ERROR',

  START_EXERCISE_REQUEST: 'START_EXERCISE_REQUEST',
  NEXT_QUESTION: 'NEXT_QUESTION',
  END_EXERCISE: 'END_EXERCISE',
  RESET_EXERCISE: 'RESET_EXERCISE',

  GET_MY_EXERCISES_REQUEST: 'GET_MY_EXERCISES_REQUEST',
  GET_MY_EXERCISES_DATA: 'GET_MY_EXERCISES_DATA',
  GET_MY_EXERCISES_ERROR: 'GET_MY_EXERCISES_ERROR',

  CREATE_EXERCISE_REQUEST: 'CREATE_EXERCISE_REQUEST',
  CREATE_EXERCISE_DATA: 'CREATE_EXERCISE_DATA',
  CREATE_EXERCISE_ERROR: 'CREATE_EXERCISE_ERROR',

  UPDATE_EXERCISE_REQUEST: 'CREATE_EXERCISE_REQUEST',
  UPDATE_EXERCISE_DATA: 'CREATE_EXERCISE_DATA',
  UPDATE_EXERCISE_ERROR: 'CREATE_EXERCISE_ERROR',

  SET_EDIT_EXERCISE: 'SET_EDIT_EXERCISE',
  UPDATE_EDIT_EXERCISE: 'UPDATE_EDIT_EXERCISE',

  // QUESTION
  CREATE_QUESTION_REQUEST: 'CREATE_QUESTION_REQUEST',
  CREATE_QUESTION_DATA: 'CREATE_QUESTION_DATA',
  CREATE_QUESTION_ERROR: 'CREATE_QUESTION_ERROR',

  DELETE_QUESTION_REQUEST: 'DELETE_QUESTION_REQUEST',
  DELETE_QUESTION_DATA: 'DELETE_QUESTION_DATA',
  DELETE_QUESTION_ERROR: 'DELETE_QUESTION_ERROR',

  UPDATE_QUESTION_REQUEST: 'UPDATE_QUESTION_REQUEST',
  UPDATE_QUESTION_DATA: 'UPDATE_QUESTION_DATA',
  UPDATE_QUESTION_ERROR: 'UPDATE_QUESTION_ERROR',

  SET_EDIT_QUESTION: 'SET_EDIT_QUESTION',
  UPDATE_EDIT_QUESTION: 'UPDATE_EDIT_QUESTION',

  UPDATE_QUESTION_ACCURACY_REQUEST: 'UPDATE_QUESTION_ACCURACY_REQUEST',
  UPDATE_QUESTION_ACCURACY_DATA: 'UPDATE_QUESTION_ACCURACY_DATA',
  UPDATE_QUESTION_ACCURACY_ERROR: 'UPDATE_QUESTION_ACCURACY_ERROR',

  // USER
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_DATA: 'SIGN_UP_DATA',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',

  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_DATA: 'SIGN_IN_DATA',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',

  SIGN_OUT: 'SIGN_OUT',
});

// To avoid side-effects
export default actionTypes;
